### ISSUE TITLE
Openbox and thinkpad x1 carbon 3gen

### ISSUE THREAD

**Issue by francozappa** [Mikachu/openbox#3]
Hi guys,

I've just installed Manjaro Linux (OB version) in my new laptop (thinkpad x1 carbon 3gen) and the UI is unusable E.g: too tiny characters, menus etc

Can you help me figuring out which is the best way to set it ?

My distro comes with two GUI tools to configure the UI 
* `obmanager` to set up OB
* `lxappearance` to switch gtk+ theme

I'm using `tint2` as system bar and `conky` to display some information

This is the first time that I have this issue because of my screen resolution (2560 by 1440)

Currently I'm using `firefox` and `thunderbird` with a huge zoom (200%) and the terminal with huge font size (30) but I'm quite unsatisfied.

Thank you very much !

**Comment by danakj** [comment]
Run obconf and increase your font sizes?

Or possibly change the DPI of your X server in your X settings?

On Thu, Nov 12, 2015 at 5:25 PM, Daniele Antonioli <notifications@github.com

**Comment by francozappa** [comment]
Thank you @danakj for your answer,

It seems that Xserver uses 96 DPI by default even with higher res display.

 Im' following those two archwiki pages:
https://wiki.archlinux.org/index.php/HiDPI
https://wiki.archlinux.org/index.php/Xorg#Display_size_and_DPI

And I've also read to use only certain DPI values (96, 120, 144, etc) to reduce scaling artifacts to GUI that use bitmaps.

The optimal value for my x1 screen should be 220 DPI but I think is too much and now I'm trying to set OB with 192 DPI.
