### ISSUE TITLE
please add option to dynamically upscale window button icons

### ISSUE THREAD

**Issue by mailinglists35** [Mikachu/openbox#5]
currently i can only enlarge window title font (which I don't want, since it goes way too big), and the only effect I get is increased spacing between minimize/maximize/close buttons, while the buttons remains at a fixed size.

what I need is truly larger buttons, as it helps me to easier click them.

thank you.
![selection_001](https://cloud.githubusercontent.com/assets/2054302/13025096/5810181e-d211-11e5-9d48-ed4fa438b995.png)

**Comment by Mikachu** [comment]
If you want larger buttons, all you have to do is make the images larger in your theme.
